- name: as   
  connection: local
  hosts: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    subnet_id: subnet-3c9a101d # i still did not understand how we will get subnet id without installing the server, 
    #since we already installed ansible server from there we got the subnet id otherwise how to know this ???
    sg_id: sg-049e25976fa9ed337 
    instances:
    - node1-ansible
    - node2-ansible
  tasks:
  - name: Install python libraries for connecting to aws
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: new node 
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
      subnet_id: "{{ subnet_id }}"
      securitygroup_id: "{{ sg_id }}" 
    loop: "{{ instances }}"   